feat: add support yarn

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -153,7 +153,16 @@ METEOR_NODE=`METEOR node -e "process.stdout.write(process.execPath)"`
 METEOR_NPM="`dirname "$METEOR_NODE"`/npm"
 
 if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
-  echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
+  echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/franciscpd/meteor-buildpack-horse.";
+  exit 1
+fi
+
+$METEOR_NPM install -g yarn
+
+METEOR_YARN=`dirname "$METEOR_NODE"`/yarn"
+
+if [ -z "$METEOR_YARN" ]; then
+  echo "FATAL: Can't find yarn within meteor bundle. This is a bug. Please open an issue at https://github.com/franciscpd/meteor-buildpack-horse.";
   exit 1
 fi
 
@@ -163,15 +172,16 @@ cp "$METEOR_NODE" "$NODE"
 chmod a+x "$NODE"
 
 # Add npm and node path so that 1.4's npm-rebuild.js will function.
-PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:$COMPILE_DIR/bin:$PATH"
+PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:`dirname $METEOR_YARN`:$COMPILE_DIR/bin:$PATH"
 
 echo "-----> Using node: `$NODE --version`"
 echo "----->    and npm: `$METEOR_NPM --version`"
+echo "----->   and yarn: `$METEOR_YARN --version`"
 
 # If we use npm on root, run npm install.  Don't use `--production` here, as we
 # may need devDependencies (e.g. webpack) in order to build the meteor app.
 if [ -e "$APP_SOURCE_DIR"/package.json ]; then
-  $METEOR_NPM install
+  $METEOR_YARN install
 fi
 
 # Related to https://github.com/meteor/meteor/issues/2796 and
@@ -203,7 +213,7 @@ rmdir $BUNDLE_DEST
 echo "-----> Installing npm production dependencies on built slug"
 if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
   cd "$COMPILE_DIR"/app/programs/server
-  $METEOR_NPM install --production
+  $METEOR_YARN install --production
   cd "$APP_SOURCE_DIR"
 fi
 
